### ISSUE TITLE
Working with data in a database part 1.

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/user_analysis#17]
Based on the data stored in the database, display:
percentage of women and men

**Comment by AnnaLangner** [comment]
I have a problem with argparse. I should have two parameters on the command line, but something is wrong with argparse, it only takes one parameter. When I type the second one, I get an error.

I  think I don't understand this documentation correctly ...
`https://docs.python.org/2/library/argparse.html#sub-commands`

**Comment by klangner** [comment]
Could you provide some example?

**Comment by AnnaLangner** [comment]
I should have invoked the command like this : `python script/main.py percentage --male` but I get an error: 
```usage: main.py [-h] {init,percentage} ...
main.py: error: unrecognized arguments: --male
```

**Comment by klangner** [comment]
Did you try:
```
python script/main.py --male percentage 
```
?
Most of the case the option flags like --male should be first.
Also you should consider to change it to:
```
python script/main.py --gender=male gender-percentage 
```

**Comment by AnnaLangner** [comment]
I changed the function call to something like this: 
`python script/main.py percentage --gender female`
