### ISSUE TITLE
Working with data in a database part 6

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/user_analysis#27]
Based on the data stored in the database, display:
The most secure password - the one that scores the most points, where:

- if it contains at least one lowercase letter, scores 1 point
- if it contains at least one capital letter, scores 2 points
- if it contains at least one digit scores 1 point
- if it contains at least 8 characters - 5 points
- if it contains a special character - 3 points

**Comment by AnnaLangner** [comment]
I don't know if I understand this command correctly ...
Should I create a new column for each password?
If someone enters the password as a parameter, should the script give points?

**Comment by klangner** [comment]
No, you need to display password with the best score.
Select all records from the database. Calculate score for them and then print password with the biggest score
