### ISSUE TITLE
Test to the function which removes special characters from the phone number

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/user_analysis#29]
which function to start testing with?

**Comment by klangner** [comment]
Ok. Lets start with testing the function which removes special characters from the phone number,

**Comment by AnnaLangner** [comment]
test to remove_special_characters_from_phone_numbers() function:
- If phone and cell without special characters -> should return phone and cell number
- If phone and cell number with special characters -> should return phone and cell number without special characters

**Comment by AnnaLangner** [comment]
How do I import my own methods for the file test?

**Comment by klangner** [comment]
Check:
https://www.tutorialspoint.com/How-to-import-other-Python-files
