### ISSUE TITLE
Building a database

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/user_analysis#3]
- loading the person.json file
- creating a table
- table data testing
- data import to SQLite

**Comment by AnnaLangner** [comment]
before importing to SQLite I should do this:

- create an additional field with the number of days remaining until the person's birthday,
- clear the phone number from special characters (only numbers should remain),
- remove the 'picture' field,
- For training purposes, the password in the form of plaintext should also be saved in the database.

Should I create new functions and call them in init_db () ??

**Comment by AnnaLangner** [comment]
Hi, I'm stuck mapping nested JSON to column, can you please send me some materials where I can find a hint on how to do this?

**Comment by klangner** [comment]
There are 2 solutions to this problem:
  1. Use multiple tables and relations
  2. Normalize (flatten out data)

Check which case you have here and choose the right solutions to it.

**Comment by AnnaLangner** [comment]
I have a problem with insert JSON into the column, I can't find how to do it, it's everywhere with panda module

I have an error:
 `sqlite3.ProgrammingError: Binding 1 has no name, but you supplied a dictionary 
(which has only names).`

**Comment by klangner** [comment]
Let's simplify it first.
In the first step assume that the database has only 2 columns:
 * First name
 * Last name
And then prepare function to load data in this kind of table.
BTW. You don't need function to flatten json. You need to flatten this structure so it will fit into table, but you can do it manually. for now leave it for step 2.

**Comment by AnnaLangner** [comment]
I change the execute in  `create_user(conn, users)` for this `cur.execute(sql, json.dumps(users,))`

and now I have this error: 
`sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1326 supplied.`

Treats every single letter as an object in column...

**Comment by klangner** [comment]
why json.dumps?
does it create valid SQL command?

**Comment by AnnaLangner** [comment]
when I have that in line 83 `cur.execute (sql, ('people', 'person',))` it works, but I don't want to write it by hand. I want it to get data from a json file.

**Comment by klangner** [comment]
I'm afraid you have to create the insert command by hand.
That's the point of this exercise. Otherwise you will use pandas for this.

**Comment by AnnaLangner** [comment]
but it doesn't make sense how I could manually insert all the original JSON?  o_O

**Comment by AnnaLangner** [comment]
maybe I should convert JSON to CSV??

**Comment by AnnaLangner** [comment]
I still have a problem with correctly inserting the json file into sqlite ... I have no idea what I am doing wrong, I still have one of these errors:

```
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 34, and there are 1 supplied.

ValueError: not enough values to unpack (expected 2, got 1)

sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 34, and there are 717 supplied.
```

**Comment by klangner** [comment]
You don't insert json. Json is a file format, not format stored in computer memory.
You need to understand what kind of structures you have after json was parsed with `json.load()` function.
And then, I assume that you know how the insert command looks like, so before calling `cur.execute(sql, str(keys,))` in line 128, try to print the value `str(keys,)` to check how it looks like. Does it looks correct?

**Comment by AnnaLangner** [comment]
I have successfully added records to the database
