### ISSUE TITLE
Create script for searching json records

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/user_analysis#5]
Name of the script: `find_record.py`
Parameters: `user name`

Return list of records with the given name.

**Comment by AnnaLangner** [comment]
I did this task, but forgot to create a new branch for it

**Comment by klangner** [comment]
This script should accept parameter `user name` and **only** print records which contains this name. Not all records.
Also it should print each record as a separate line.

**Comment by AnnaLangner** [comment]
I created a new PR

**Comment by AnnaLangner** [comment]
I cleaned up everything

**Comment by klangner** [comment]
Ok.  It looks that I need to clarify this:
Given the command:
```
python script/find_record.py init/persons.json Ala
```
It should print:
```
Ala, Kowalska, female, ...
Ala, Brown, female,...
```
